[package]
name = "plump-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
rand = "0.8.5"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.44.0", features = [
    "Win32_System_Console",
    "Win32_Foundation",
] }
