name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rustc version
      run: rustc --version --verbose

    - name: Cargo version
      run: cargo --version --verbose

    - name: Rustup version
      run: Rustup --version --verbose

    - name: Run tests
      run: cargo test

    - name: Run formatting check
      run: cargo fmt --check

    - name: Run check
      run: cargo check

    - name: Run clippy
      run: cargo clippy
